export const newImagePaths = [
  {
    name: 'Gattoo Chair',
    path: '/optimized/gattochair.webp',
    group: 'Monster 3.0',
    productId: '67b590d0e03cc2c55c624a5e',
  },
  {
    name: 'Monster Bench',
    path: '/optimized/monster3bench.webp',
    group: 'Monster 3.0',
    productId: '67b590b8e03cc2c55c624a5b',
  },
  {
    name: 'Monster Dining Chair',
    path: '/optimized/monster3diningchair.webp',
    group: 'Monster 3.0',
    productId: '67b59060e03cc2c55c624a4e',
  },
  {
    name: 'Monster Console',
    path: '/optimized/monster3console2.webp',
    group: 'Monster 3.0',
    productId: '67b59041e03cc2c55c624a4b',
  },
  {
    name: 'Monster Dining Kids Chair',
    path: '/optimized/monster3kidschair.webp',
    group: 'Monster 3.0',
    productId: '67b5e69de03cc2c55c62bd22',
  },
  {
    name: 'Monster Planter',
    path: '/optimized/monster3planter.webp',
    group: 'Monster 3.0',
    productId: '67b59111e03cc2c55c624a64',
  },
  {
    name: 'Monster Dining Table',
    path: '/optimized/monster3diningtable.webp',
    group: 'Monster 3.0',
    productId: '67b59097e03cc2c55c624a54',
  },
  {
    name: 'Monster Library',
    path: '/optimized/monster3lib.webp',
    group: 'Monster 3.0',
    productId: '67b590a6e03cc2c55c624a58',
  },
  {
    name: 'Monsformer',
    path: '/optimized/monsformer.webp',
    group: 'Monsformer',
    productId: '67a5fa324da9b29cd0f10c3a',
  },
  {
    name: 'Console 1',
    path: '/optimized/matildaconsole1.webp',
    group: 'Matilda',
    productId: '67a5ec684da9b29cd0f10b8e',
  },
  {
    name: 'Console 2',
    path: '/optimized/matildaconsole2.webp',
    group: 'Matilda',
    productId: '67a5ec804da9b29cd0f10b98',
  },
  {
    name: 'Monster Basin',
    path: '/optimized/monster1basin.webp',
    group: 'Monster 1.0',
    productId: '67a5e7ce4da9b29cd0f10b51',
  },
  {
    name: 'Planter',
    path: '/optimized/matildaplanter.webp',
    group: 'Matilda',
    productId: '67a5eedf4da9b29cd0f10bd0',
  },
  {
    name: 'Monster Bathtub',
    path: '/optimized/monster1bathtub.webp',
    group: 'Monster 1.0',
    productId: '67a5e9914da9b29cd0f10b58',
  },
  {
    name: 'Coffee table',
    path: '/optimized/matildacoffeetable.webp',
    group: 'Matilda',
    productId: '67a5ecc44da9b29cd0f10ba2',
  },
  {
    name: 'Library',
    path: '/optimized/matildalib.webp',
    group: 'Matida',
    productId: '67a5ec084da9b29cd0f10b7e',
  },
  {
    name: 'Bench 1',
    path: '/optimized/matildabench1.webp',
    group: 'Matilda',
    productId: '67bc49a855b639fb58349ec7',
  },
  {
    name: 'U-Table',
    path: '/optimized/matildautable.webp',
    group: 'Matilda',
    productId: '67a5ef304da9b29cd0f10bea',
  },
  {
    name: 'Side Table',
    path: '/optimized/matildasidetable.webp',
    group: 'Matilda',
    productId: '67a5eef74da9b29cd0f10be1',
  },
  {
    name: 'Monster Binty',
    path: '/optimized/monstercbinty.webp',
    group: 'Monster Collectibles',
    productId: '67a5efc74da9b29cd0f10c11',
  },
  {
    name: 'Chair',
    path: '/optimized/matildachair.webp',
    group: 'Matilda',
    productId: '67a5ef664da9b29cd0f10bfb',
  },
  {
    name: 'Monster Squinty',
    path: '/optimized/monstersquinty.webp',
    group: 'Monster Collectibles',
    productId: '67a5f8544da9b29cd0f10c31',
  },
  {
    name: 'Console 1',
    path: '/optimized/matildaconsole1_2.webp',
    group: 'Matilda',
    productId: '67a5ec684da9b29cd0f10b8e',
  },
  {
    name: 'Center Table 1',
    path: '/optimized/matildacentertable.webp',
    group: 'Matilda',
    productId: '67a5ece24da9b29cd0f10bac',
  },
  {
    name: 'Center Table 2',
    path: '/optimized/matildacentertable2.webp',
    group: 'Matilda',
    productId: '67a5ecf94da9b29cd0f10bb6',
  },
  {
    name: 'Table Lamp',
    path: '/optimized/matildatablelamp.webp',
    group: 'Matilda',
    productId: '67a5ebf14da9b29cd0f10b77',
  },
  {
    name: 'Yoda',
    path: '/optimized/yoda.webp',
    group: 'Monster 2.0',
    productId: '67a5eb9f4da9b29cd0f10b71',
  },
  {
    name: 'Bathtub',
    path: '/optimized/matildabathtub.webp',
    group: 'Matilda',
    productId: '67a5ef4c4da9b29cd0f10bf4',
  },
  {
    name: 'Floor Lamp',
    path: '/optimized/matildafloorlamp.webp',
    group: 'Matilda',
    productId: '67a5ef974da9b29cd0f10c0a',
  },
  {
    name: 'Monster Brainy',
    path: '/optimized/brainy.webp',
    group: 'Monster Collectibles',
    productId: '67a5f5c14da9b29cd0f10c17',
  },
  {
    name: 'Monster Gattoofer',
    path: '/optimized/gattooffer.webp',
    group: 'Monster Collectibles',
    productId: '67a5f5ea4da9b29cd0f10c1c',
  },
  // {
  //   name: 'image-31',
  //   path: 'https://7h4qznnnsa.ufs.sh/f/8EYZaNz64oKUghzY8mlLdSN8CY5rJGOAxcqQpM9fjoh4etX6',
  //   group: '',
  //   productId: '',
  // },
  {
    name: 'Monster Grumpy',
    path: '/optimized/grumpy.webp',
    group: 'Monster Collectibles',
    productId: '67a5f8394da9b29cd0f10c2c',
  },
  {
    name: 'Monster Chandelier',
    path: '/optimized/monster3chandelier.webp',
    group: 'Monster 3.0',
    productId: '67b590e8e03cc2c55c624a61',
  },
  {
    name: 'Flower Vase',
    path: '/optimized/matildaflowervase.webp',
    group: 'Matilda',
    productId: '67a5ed9e4da9b29cd0f10bc6',
  },
  {
    name: 'Monster Gum',
    path: '/optimized/gum.webp',
    group: 'Monster Collectibles',
    productId: '67a5f6834da9b29cd0f10c27',
  },
  {
    name: 'Monster Guard',
    path: '/optimized/guard.webp',
    group: 'Monster Collectibles',
    productId: '67a5f6534da9b29cd0f10c22',
  },
  {
    name: 'Partition Screen',
    path: '/optimized/matildaps.webp',
    group: 'Matilda',
    productId: '67a5ec494da9b29cd0f10b87',
  },
  {
    name: 'Gattoo X Top Brewer',
    path: '/optimized/topbrewer.webp',
    group: 'Monster 2.0',
    productId: '67a5eb7e4da9b29cd0f10b69',
  },
  {
    name: 'Basin',
    path: '/optimized/matildabasin.webp',
    group: 'Matilda',
    productId: '67a5ed3c4da9b29cd0f10bbf',
  },
  {
    name: 'Monster Console',
    path: '/optimized/monster1console.webp',
    group: 'Monster 1.0',
    productId: '67a5eaba4da9b29cd0f10b63',
  },
  {
    name: 'Planter',
    path: '/optimized/matildaplanter2.webp',
    group: 'Matilda',
    productId: '67a5eedf4da9b29cd0f10bd0',
  },
  {
    name: 'Samaveta Bench',
    path: '/optimized/samavetabench.webp',
    group: 'KD X Serafini',
    productId: '67a5fa124da9b29cd0f10c36',
  },
  {
    name: 'Monster Planter',
    path: '/optimized/monster3planter2.webp',
    group: 'Monster 3.0',
    productId: '67b59111e03cc2c55c624a64',
  },
  {
    name: 'Bench 2',
    path: '/optimized/matildabench2.webp',
    group: 'Matilda',
    productId: '67a5ef7f4da9b29cd0f10c05',
  },
  {
    name: 'Dining Table',
    path: '/optimized/matildadining.webp',
    group: 'Matilda',
    productId: '67ef850f629882967f3fbb3d',
  },
  {
    name: 'Monster Buddha',
    path: '/optimized/buddha.webp',
    group: 'Monster Collectibles',
    productId: '67f4da6bd5986748ae8f34fe',
  },
  {
    name: 'Monster Humpty',
    path: '/optimized/humpty.webp',
    group: 'Monster Collectibles',
    productId: '67efa13d38f60435b89ba291',
  },
  {
    name: 'KD Desk',
    path: '/optimized/kddesk.webp',
    group: 'Matilda',
    productId: '67a5eef74da9b29cd0f10be221',
  },
  {
    name: 'Office Mirror',
    path: '/optimized/officemirror.webp',
    group: 'Matilda',
    productId: '67a5eef74da9b29cd0f10be2219',
  },
  {
    name: 'Wash Basin',
    path: '/optimized/matildawashbasin.webp',
    group: 'Matilda',
    productId: '67a5eef74da9b29cd0f10be22191',
  },
  {
    name: 'EA Bar',
    path: '/optimized/eabar.webp',
    group: 'EA_Bar',
    productId: '67a5eef74da9b29cd0f10be221912',
  },
  {
    name: 'Conference Monster Table',
    path: '/optimized/conferencemonster.webp',
    group: 'conference_monster',
    productId: '67a5eef74da9b29cd0f10be2219112',
  },
  {
    name: 'Samaveta Console',
    path: '/optimized/samavetaconsole.webp',
    group: 'KD X Serafini',
    productId: 'samaveta-console',
  },
  {
    name: '86 Side Table',
    path: '/optimized/86sidetable.webp',
    group: 'Matilda',
    productId: '86-side-table',
  },
  {
    name: '86 Chest of Drawer',
    path: '/optimized/86chestofdrawer.webp',
    group: 'Matilda',
    productId: '86-chest-of-drawer',
  },
  {
    name: 'Chaise Longue',
    path: '/optimized/chaiselongue.webp',
    group: 'Matilda',
    productId: 'chaise-longue',
  },
  {
    name: 'Marble Ball Console',
    path: '/optimized/marbleballconsole.webp',
    group: 'Matilda',
    productId: 'marble-ball-console',
  },
  {
    name: 'Marble Console',
    path: '/optimized/marbleconsole.webp',
    group: 'Matilda',
    productId: 'marble-console',
  },
  {
    name: 'Marble Screen',
    path: '/optimized/marblescreen.webp',
    group: 'Matilda',
    productId: 'marble-screen',
  },
  {
    name: 'Side Table',
    path: '/optimized/matildasidetable2.webp',
    group: 'Matilda',
    productId: 'side-table',
  },
  {
    name: 'Taavdi',
    path: '/optimized/taavdi.webp',
    group: 'Matilda 2025',
    productId: 'taavdi',
  },
  {
    name: 'Bench',
    path: '/optimized/matilda2023bench.webp',
    group: 'Matilda 2023',
    productId: 'tfh-bench',
  },
  {
    name: 'AV Console',
    path: '/optimized/avconsole.webp',
    group: 'Matilda 2023',
    productId: 'tfh-av-console',
  },
  {
    name: 'Console 1',
    path: '/optimized/matilda23console1.webp',
    group: 'Matilda 2023',
    productId: 'tfh-console-travertine',
  },
  {
    name: 'Side Table',
    path: '/optimized/matilda23sidetable.webp',
    group: 'Matilda 2023',
    productId: 'tfh-side-table',
  },
  {
    name: 'Monster Dining Kids Chair',
    path: '/optimized/monsterdiningkidschair.webp',
    group: 'Monster 3.0',
    productId: '67b5e69de03cc2c55c62bd22',
  },
  {
    name: 'Monster Ottoman',
    path: '/optimized/monsterottoman.webp',
    group: 'Monster 3.0',
    productId: 'monster-ottoman',
  },
  {
    name: 'Tea Bar',
    path: '/optimized/teabar.webp',
    group: 'Matilda 2022',
    productId: 'tdp-tea-bar',
  },
  {
    name: 'Monster Center Table',
    path: '/optimized/m3centertable.webp',
    group: 'Monster 3.1',
    productId: 'monster3centertable',
  },
  {
    name: 'Monster Coffee Table',
    path: '/optimized/m3coffeetable.webp',
    group: 'Monster 3.1',
    productId: 'monster3coffeetable',
  },
  {
    name: 'Monster Console',
    path: '/optimized/m3console.webp',
    group: 'Monster 3.1',
    productId: 'monster3console',
  },
  {
    name: 'Monster Console Storage',
    path: '/optimized/m3consolestorage.webp',
    group: 'Monster 3.1',
    productId: 'monster3consolestorage',
  },
  {
    name: 'Monster Desk',
    path: '/optimized/m3desk.webp',
    group: 'Monster 3.1',
    productId: 'monster3desk',
  },
  {
    name: 'Monster FloorLamp',
    path: '/optimized/m3floorlamp.webp',
    group: 'Monster 3.1',
    productId: 'monster3floorlamp',
  },
  {
    name: 'Monster Long Dining Table',
    path: '/optimized/m3longdiningtable.webp',
    group: 'Monster 3.1',
    productId: 'monster3longdiningtable',
  },
  {
    name: 'Monster Mirror',
    path: '/optimized/m3mirror.webp',
    group: 'Monster 3.1',
    productId: 'monster3monstermirror',
  },
  {
    name: 'Monster Round Dining Table',
    path: '/optimized/m3rounddining.webp',
    group: 'Monster 3.1',
    productId: 'monster3rounddining',
  },
  {
    name: 'Monster Single Shelving Unit',
    path: '/optimized/m3shelves.webp',
    group: 'Monster 3.1',
    productId: 'monster3shelves',
  },
  {
    name: 'Monster Side Table',
    path: '/optimized/m3sidetable.webp',
    group: 'Monster 3.1',
    productId: 'monster3sidetable',
  },

  ...Array(2)
    .fill([
      {
        name: 'Gattoo Chair',
        path: '/optimized/gattochair.webp',
        group: 'Monster 3.0',
        productId: '67b590d0e03cc2c55c624a5e',
      },
      {
        name: 'Monster Bench',
        path: '/optimized/monster3bench.webp',
        group: 'Monster 3.0',
        productId: '67b590b8e03cc2c55c624a5b',
      },
      {
        name: 'Monster Dining Chair',
        path: '/optimized/monster3diningchair.webp',
        group: 'Monster 3.0',
        productId: '67b59060e03cc2c55c624a4e',
      },
      {
        name: 'Monster Console',
        path: '/optimized/monster3console2.webp',
        group: 'Monster 3.0',
        productId: '67b59041e03cc2c55c624a4b',
      },
      {
        name: 'Monster Dining Kids Chair',
        path: '/optimized/monster3kidschair.webp',
        group: 'Monster 3.0',
        productId: '67b5e69de03cc2c55c62bd22',
      },
      {
        name: 'Monster Planter',
        path: '/optimized/monster3planter.webp',
        group: 'Monster 3.0',
        productId: '67b59111e03cc2c55c624a64',
      },
      {
        name: 'Monster Dining Table',
        path: '/optimized/monster3diningtable.webp',
        group: 'Monster 3.0',
        productId: '67b59097e03cc2c55c624a54',
      },
      {
        name: 'Monster Library',
        path: '/optimized/monster3lib.webp',
        group: 'Monster 3.0',
        productId: '67b590a6e03cc2c55c624a58',
      },
      {
        name: 'Monsformer',
        path: '/optimized/monsformer.webp',
        group: 'Monsformer',
        productId: '67a5fa324da9b29cd0f10c3a',
      },
      {
        name: 'Console 1',
        path: '/optimized/matildaconsole1.webp ',
        group: 'Matilda',
        productId: '67a5ec684da9b29cd0f10b8e',
      },
      {
        name: 'Console 2',
        path: '/optimized/matildaconsole2.webp',
        group: 'Matilda',
        productId: '67a5ec804da9b29cd0f10b98',
      },
      {
        name: 'Monster Basin',
        path: '/optimized/monster1basin.webp',
        group: 'Monster 1.0',
        productId: '67a5e7ce4da9b29cd0f10b51',
      },
      {
        name: 'Planter',
        path: '/optimized/matildaplanter.webp',
        group: 'Matilda',
        productId: '67a5eedf4da9b29cd0f10bd0',
      },
      {
        name: 'Monster Bathtub',
        path: '/optimized/monster1bathtub.webp',
        group: 'Monster 1.0',
        productId: '67a5e9914da9b29cd0f10b58',
      },
      {
        name: 'Coffee table',
        path: '/optimized/matildacoffeetable.webp',
        group: 'Matilda',
        productId: '67a5ecc44da9b29cd0f10ba2',
      },
      {
        name: 'Library',
        path: '/optimized/matildalib.webp',
        group: 'Matida',
        productId: '67a5ec084da9b29cd0f10b7e',
      },
      {
        name: 'Bench 1',
        path: '/optimized/matildabench1.webp',
        group: 'Matilda',
        productId: '67bc49a855b639fb58349ec7',
      },
      {
        name: 'U-Table',
        path: '/optimized/matildautable.webp',
        group: 'Matilda',
        productId: '67a5ef304da9b29cd0f10bea',
      },
      {
        name: 'Side Table',
        path: '/optimized/matildasidetable.webp',
        group: 'Matilda',
        productId: '67a5eef74da9b29cd0f10be1',
      },
      {
        name: 'Monster Binty',
        path: '/optimized/monstercbinty.webp',
        group: 'Monster Collectibles',
        productId: '67a5efc74da9b29cd0f10c11',
      },
      {
        name: 'Chair',
        path: '/optimized/matildachair.webp',
        group: 'Matilda',
        productId: '67a5ef664da9b29cd0f10bfb',
      },
      {
        name: 'Monster Squinty',
        path: '/optimized/monstersquinty.webp',
        group: 'Monster Collectibles',
        productId: '67a5f8544da9b29cd0f10c31',
      },
      {
        name: 'Console 1',
        path: '/optimized/matildaconsole1_2.webp',
        group: 'Matilda',
        productId: '67a5ec684da9b29cd0f10b8e',
      },
      {
        name: 'Center Table 1',
        path: '/optimized/matildacentertable.webp',
        group: 'Matilda',
        productId: '67a5ece24da9b29cd0f10bac',
      },
      {
        name: 'Center Table 2',
        path: '/optimized/matildacentertable2.webp',
        group: 'Matilda',
        productId: '67a5ecf94da9b29cd0f10bb6',
      },
      {
        name: 'Table Lamp',
        path: '/optimized/matildatablelamp.webp',
        group: 'Matilda',
        productId: '67a5ebf14da9b29cd0f10b77',
      },
      {
        name: 'Yoda',
        path: '/optimized/yoda.webp',
        group: 'Monster 2.0',
        productId: '67a5eb9f4da9b29cd0f10b71',
      },
      {
        name: 'Bathtub',
        path: '/optimized/matildabathtub.webp',
        group: 'Matilda',
        productId: '67a5ef4c4da9b29cd0f10bf4',
      },
      {
        name: 'Floor Lamp',
        path: '/optimized/matildafloorlamp.webp',
        group: 'Matilda',
        productId: '67a5ef974da9b29cd0f10c0a',
      },
      {
        name: 'Monster Brainy',
        path: '/optimized/brainy.webp',
        group: 'Monster Collectibles',
        productId: '67a5f5c14da9b29cd0f10c17',
      },
      {
        name: 'Monster Gattoofer',
        path: '/optimized/gattooffer.webp',
        group: 'Monster Colection',
        productId: '67a5f5ea4da9b29cd0f10c1c',
      },
      // {
      //   name: 'image-31',
      //   path: 'https://7h4qznnnsa.ufs.sh/f/8EYZaNz64oKUghzY8mlLdSN8CY5rJGOAxcqQpM9fjoh4etX6',
      //   group: '',
      //   productId: '',
      // },
      {
        name: 'Monster Grumpy',
        path: '/optimized/grumpy.webp',
        group: 'Monster Collectibles',
        productId: '67a5f8394da9b29cd0f10c2c',
      },
      {
        name: 'Monster Chandelier',
        path: '/optimized/monster3chandelier.webp',
        group: 'Monster 3.0',
        productId: '67b590e8e03cc2c55c624a61',
      },
      {
        name: 'Flower Vase',
        path: '/optimized/matildaflowervase.webp',
        group: 'Matilda',
        productId: '67a5ed9e4da9b29cd0f10bc6',
      },
      {
        name: 'Monster Gum',
        path: '/optimized/gum.webp',
        group: 'Monster Collectibles',
        productId: '67a5f6834da9b29cd0f10c27',
      },
      {
        name: 'Monster Guard',
        path: '/optimized/guard.webp',
        group: 'Monster Collectibles',
        productId: '67a5f6534da9b29cd0f10c22',
      },
      {
        name: 'Partition Screen',
        path: '/optimized/matildaps.webp',
        group: 'Matilda',
        productId: '67a5ec494da9b29cd0f10b87',
      },
      {
        name: 'Gattoo X Top Brewer',
        path: '/optimized/topbrewer.webp',
        group: 'Monster 2.0',
        productId: '67a5eb7e4da9b29cd0f10b69',
      },
      {
        name: 'Basin',
        path: '/optimized/matildabasin.webp',
        group: 'Matilda',
        productId: '67a5ed3c4da9b29cd0f10bbf',
      },
      {
        name: 'Monster Console',
        path: '/optimized/monster1console.webp',
        group: 'Monster 1.0',
        productId: '67a5eaba4da9b29cd0f10b63',
      },
      {
        name: 'Planter',
        path: '/optimized/matildaplanter2.webp',
        group: 'Matilda',
        productId: '67a5eedf4da9b29cd0f10bd0',
      },
      {
        name: 'Samaveta Bench',
        path: '/optimized/samavetabench.webp',
        group: 'KD X Serafini',
        productId: '67a5fa124da9b29cd0f10c36',
      },
      {
        name: 'Monster Planter',
        path: '/optimized/monster3planter2.webp',
        group: 'Monster 3.0',
        productId: '67b59111e03cc2c55c624a64',
      },
      {
        name: 'Bench 2',
        path: '/optimized/matildabench2.webp',
        group: 'Matilda',
        productId: '67a5ef7f4da9b29cd0f10c05',
      },
      {
        name: 'Dining Table',
        path: '/optimized/matildadining.webp',
        group: 'Matilda',
        productId: '67ef850f629882967f3fbb3d',
      },
      {
        name: 'Monster Buddha',
        path: '/optimized/buddha.webp',
        group: 'Monster Collectibles',
        productId: '67f4da6bd5986748ae8f34fe',
      },
      {
        name: 'Monster Humpty',
        path: '/optimized/humpty.webp',
        group: 'Monster Collectibles',
        productId: '67efa13d38f60435b89ba291',
      },
      {
        name: 'KD Desk',
        path: '/optimized/kddesk.webp',
        group: 'Matilda',
        productId: '67a5eef74da9b29cd0f10be221',
      },
      {
        name: 'Office Mirror',
        path: '/optimized/officemirror.webp',
        group: 'Matilda',
        productId: '67a5eef74da9b29cd0f10be2219',
      },
      {
        name: 'Wash Basin',
        path: '/optimized/matildawashbasin.webp',
        group: 'Matilda',
        productId: '67a5eef74da9b29cd0f10be22191',
      },
      {
        name: 'Samaveta Console',
        path: '/optimized/samavetaconsole.webp',
        group: 'KD X Serafini',
        productId: 'samaveta-console',
      },
      {
        name: '86 Side Table',
        path: '/optimized/86sidetable.webp',
        group: 'Matilda',
        productId: '86-side-table',
      },
      {
        name: '86 Chest of Drawer',
        path: '/optimized/86chestofdrawer.webp',
        group: 'Matilda',
        productId: '86-chest-of-drawer',
      },
      {
        name: 'Chaise Longue',
        path: '/optimized/chaiselongue.webp',
        group: 'Matilda',
        productId: 'chaise-longue',
      },
      {
        name: 'Marble Ball Console',
        path: '/optimized/marbleballconsole.webp',
        group: 'Matilda',
        productId: 'marble-ball-console',
      },
      {
        name: 'Marble Console',
        path: '/optimized/marbleconsole.webp',
        group: 'Matilda',
        productId: 'marble-console',
      },
      {
        name: 'Marble Screen',
        path: '/optimized/marblescreen.webp',
        group: 'Matilda',
        productId: 'marble-screen',
      },
      {
        name: 'Side Table',
        path: '/optimized/matildasidetable2.webp',
        group: 'Matilda',
        productId: 'side-table',
      },
      {
        name: 'Taavdi',
        path: '/optimized/taavdi.webp',
        group: 'Matilda 2025',
        productId: 'taavdi',
      },
      {
        name: 'Bench',
        path: '/optimized/matilda2023bench.webp',
        group: 'Matilda 2023',
        productId: 'tfh-bench',
      },
      {
        name: 'AV Console',
        path: '/optimized/avconsole.webp',
        group: 'Matilda 2023',
        productId: 'tfh-av-console',
      },
      {
        name: 'Console 1',
        path: '/optimized/matilda23console1.webp',
        group: 'Matilda 2023',
        productId: 'tfh-console-travertine',
      },
      {
        name: 'Side Table',
        path: '/optimized/matilda23sidetable.webp',
        group: 'Matilda 2023',
        productId: 'tfh-side-table',
      },
      {
        name: 'Monster Dining Kids Chair',
        path: '/optimized/monsterdiningkidschair.webp',
        group: 'Monster 3.0',
        productId: '67b5e69de03cc2c55c62bd22',
      },
      {
        name: 'Monster Ottoman',
        path: '/optimized/monsterottoman.webp',
        group: 'Monster 3.0',
        productId: 'monster-ottoman',
      },
      {
        name: 'Tea Bar',
        path: '/optimized/teabar.webp',
        group: 'Matilda 2022',
        productId: 'tdp-tea-bar',
      },
      {
        name: 'Monster Center Table',
        path: '/optimized/m3centertable.webp',
        group: 'Monster 3.1',
        productId: 'monster3centertable',
      },
      {
        name: 'Monster Coffee Table',
        path: '/optimized/m3coffeetable.webp',
        group: 'Monster 3.1',
        productId: 'monster3coffeetable',
      },
      {
        name: 'Monster Console',
        path: '/optimized/m3console.webp',
        group: 'Monster 3.1',
        productId: 'monster3console',
      },
      {
        name: 'Monster Console Storage',
        path: '/optimized/m3consolestorage.webp',
        group: 'Monster 3.1',
        productId: 'monster3consolestorage',
      },
      {
        name: 'Monster Desk',
        path: '/optimized/m3desk.webp',
        group: 'Monster 3.1',
        productId: 'monster3desk',
      },
      {
        name: 'Monster FloorLamp',
        path: '/optimized/m3floorlamp.webp',
        group: 'Monster 3.1',
        productId: 'monster3floorlamp',
      },
      {
        name: 'Monster Long Dining Table',
        path: '/optimized/m3longdiningtable.webp',
        group: 'Monster 3.1',
        productId: 'monster3longdiningtable',
      },
      {
        name: 'Monster Mirror',
        path: '/optimized/m3mirror.webp',
        group: 'Monster 3.1',
        productId: 'monster3monstermirror',
      },
      {
        name: 'Monster Round Dining Table',
        path: '/optimized/m3rounddining.webp',
        group: 'Monster 3.1',
        productId: 'monster3rounddining',
      },
      {
        name: 'Monster Single Shelving Unit',
        path: '/optimized/m3shelves.webp',
        group: 'Monster 3.1',
        productId: 'monster3shelves',
      },
      {
        name: 'Monster Side Table',
        path: '/optimized/m3sidetable.webp',
        group: 'Monster 3.1',
        productId: 'monster3sidetable',
      },
    ])
    .flat(),
];
